"""Realistic demo AI responses. No Gemini/OpenAI calls."""

CATALOG_SAMPLES = [
    {
        "title": "Kutch Artisanal Terracotta Painted Vase",
        "hindiTitle": "कच्छ हस्तनिर्मित मिट्टी का मांडणा फूलदान",
        "story": "Individually thrown on a traditional foot-spun potter wheel, this vessel honors time-tested artisan methods. The organic clay breathes naturally, decorated with auspicious tribal motifs using mineral clay pigments.",
        "hindiStory": "पारंपरिक पैर से चलने वाले चाक पर निर्मित यह फूलदान प्राचीन शिल्प परंपरा को सहेजता है। प्राकृतिक मिट्टी और खनिज रंगों का उपयोग कर इसे तैयार किया गया है।",
        "category": "Pottery",
        "materials": "Alluvial Terracotta Clay & Mineral White Pigments",
        "craftTechnique": "Foot-Spun Wheel & Wood Kiln Curing",
        "craftOrigin": "Bhuj, Kutch",
        "tags": ["Pottery", "Eco-friendly", "Mandana Art", "Handmade", "Terracotta"],
    },
    {
        "title": "Terracotta Hand-Painted Heritage Vase",
        "hindiTitle": "हस्तनिर्मित मिट्टी का चित्रित फूलदान",
        "story": "In the heart of rural Gujarat, the rhythmic turning of the potter's wheel has been preserved across generations. This terracotta vase is shaped by hand using alluvial river silt, sun-dried for 48 hours, and decorated with freehand tribal motifs painted using fine bamboo brushes and rice paste.",
        "hindiStory": "गुजरात के ग्रामीण अंचल में, कुम्हार के चाक की निरंतर गति तीन पीढ़ियों से हमारे परिवार की धड़कन रही है। यह मटका प्राकृतिक नदी की मिट्टी से बना है और इसे धूप में पकाकर प्राकृतिक रंगों से सजाया गया है।",
        "category": "Pottery",
        "materials": "Natural River Clay, Organic Rice Paste White Pigments",
        "craftTechnique": "Wheel Throwing & Sun Curing",
        "craftOrigin": "Kutch Heritage, Gujarat",
        "tags": ["Home Decor", "Terracotta", "Natural Dyes", "Heritage Clay", "Handmade"],
    },
    {
        "title": "Authentic Terracotta Earth Vase with Tribal Art",
        "hindiTitle": "पारंपरिक जनजातीय मांडणा मिट्टी का फूलदान",
        "story": "Formed with reverence for the earth, this artisan vase brings rustic warmth and Indian craft mastery to contemporary living spaces. Completely non-toxic, sustainable, and handmade.",
        "hindiStory": "धरती के प्रति कृतज्ञता से बना यह शिल्प आपके घर को पारंपरिक भारतीय कला की शोभा प्रदान करता है। पूर्णतः विषमुक्त और पर्यावरण-अनुकूल।",
        "category": "Pottery",
        "materials": "Kutch River Clay & Natural Earth Dyes",
        "craftTechnique": "Hand Throwing & Natural Sun Baking",
        "craftOrigin": "Kutch Craft Cluster",
        "tags": ["Vase", "Tribal Art", "Sustainable", "Artisan Made", "Vessel"],
    },
]


def demo_catalog(payload: dict | None = None) -> dict:
    payload = payload or {}
    seed = abs(hash((payload.get("title") or "") + (payload.get("transcript") or ""))) % len(CATALOG_SAMPLES)
    sample = dict(CATALOG_SAMPLES[seed])
    if payload.get("category"):
        sample["category"] = payload["category"]
    sample["is_demo"] = True
    sample["note"] = "Demo catalog text. Real Gemini/OpenAI generation is not connected yet."
    return sample


def demo_story(payload: dict | None = None) -> dict:
    catalog = demo_catalog(payload)
    return {
        "story": catalog["story"],
        "hindiStory": catalog["hindiStory"],
        "is_demo": True,
        "note": "Demo story. Not generated by an external AI API.",
    }


def demo_enhance_image(image_url: str | None) -> dict:
    fallback = "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=80"
    return {
        "original_image": image_url or fallback,
        "enhanced_image": image_url or fallback,
        "is_demo": True,
        "note": "Demo enhance: the same image is returned. Studio-quality AI enhancement is not implemented yet.",
    }


def demo_transcribe(payload: dict | None = None) -> dict:
    payload = payload or {}
    transcript = payload.get("transcript") or (
        "यह एक हस्तशिल्प मिट्टी का मटका है, जिसे मैंने अपने हाथों से बनाया है। "
        "इसकी खास बात यह है कि यह पानी को प्राकृतिक रूप से ठंडा रखता है।"
    )
    english = payload.get("english") or (
        "This handcrafted terracotta pot is shaped using natural riverbed clay, "
        "naturally cooling water through organic evaporative cooling."
    )
    return {
        "transcript": transcript,
        "detected_language": payload.get("language") or "hi",
        "english_description": english,
        "is_demo": True,
        "note": "Demo transcription. Speech-to-text is not connected to a real model yet.",
    }
